---
- name: Configure base system
  hosts: all
  become: true
  roles:
    - common
    - containerd
    - kubernetes

- name: Init k8s master node
  hosts: master
  become: true
  roles:
    - k8s_master
    
- name: Join k8s master node with workers
  hosts: workers
  become: true
  roles:
    - k8s_worker


